import "@/styles/tailwind.css";

import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";

export const metadata: Metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const Layout: FC<PropsWithChildren> = ({ children }) => (
	<html lang="pt-BR">
		<body>{children}</body>
	</html>
);

export default Layout;
